version: '3'

services:
   couchbase:
      build: .
      ports:
         - '8091:8091'
         - '8092:8092'
         - '8093:8093'
         - '11210:11210'
      volumes:
         - couchbase-data:/opt/couchbase/var
      environment:
         - COUCHBASE_ADMIN_USER=root
         - COUCHBASE_ADMIN_PASSWORD=password

volumes:
   couchbase-data:
